### ISSUE TITLE
Broken Download Link - Converting VDV-452 to GTFS

### ISSUE THREAD

**Issue by djdcc** [OneBusAway/onebusaway-vdv-modules#12]
Hi Team,

I wish to convert a VDV transit feed to GTFS, but I'm not able to download the executable jar file from the link on the "onebusaway-vdv-modules" repository. Please help me!

The link url:
http://nexus.onebusaway.org/service/local/artifact/maven/content?r=public&g=org.onebusaway&a=onebusaway-vdv452-to-gtfs-converter-cli&v=LATEST

Thanks,
@djdcc

**Comment by barbeau** [comment]
Thanks for reporting! I've fixed the link in https://github.com/OneBusAway/onebusaway-vdv-modules/commit/91e861cdc26a6788189ddef30acdce082a25c3f3 and updated the README. The new format is:
http://nexus.onebusaway.org/service/local/artifact/maven/content?r=public&g=org.onebusaway&a=onebusaway-vdv452-to-gtfs-converter-cli&v=LATEST

You can see a directory listing here:
http://nexus.onebusaway.org/nexus/content/repositories/snapshots/org/onebusaway/onebusaway-vdv452-to-gtfs-converter-cli/1.0.0-SNAPSHOT/
