### ISSUE TITLE
Stop types in EStopType.java

### ISSUE THREAD

**Issue by stkdiretto** [OneBusAway/onebusaway-vdv-modules#5]
EStopType.java only allows `1` and `2` for `ONR_TYP_NR` – VDV-452, however, allows this to be any value from 1..5
Is there a reason for constraining the model to 1 and 2?

**Comment by bufemc** [comment]
Yes. 1 is a station, 2 a depot, others IMHO not of interest for public transport.
You can either remove all entries with an ONR_TYP_NR >= 3, or:
I just modified EStopType.java and added another ENUM SKIP, and replaced the else branch with
return SKIP;

Here is the list of stop types (German):

"
Bezeichner des funktionalen Typs eines Ortes <Ortstyp>
1: Haltepunkt
2: Betriebshofpunkt
3: Ortsmarke
4: LSA-Punkt
5: Routenzwischenpunkt
6: Betriebspunkt
7: Grenzpunkt
"

**Comment by bufemc** [comment]
I also made some modifications so only stops with ONR_TYP_NR=1 are exported to stops.txt and stop_times.txt .. but that might be a too individual modification, so I will just post it here, it might be helpful for others, too.

      boolean isGtfsStop = (vdvStop.getId().getType() == org.onebusaway.vdv452.model.EStopType.STOP);
..
      if (isGtfsStop) {
    	  _out.saveEntity(gtfsStop);
      }
..
      if (isGtfsStop) {
    	  _out.saveEntity(stopTime);
      }

**Comment by bufemc** [comment]
Better later than never: as I see this issue was fixed, you can close it.

**Comment by barbeau** [comment]
Fixed in https://github.com/OneBusAway/onebusaway-vdv-modules/pull/7. Thanks @bufemc!
