### ISSUE TITLE
Broken link to jar file

### ISSUE THREAD

**Issue by ustroetz** [OneBusAway/onebusaway-vdv-modules#8]
The link to the jar file is unfortunately broken. Is this still hosted anywhere else? I am happy to fix the readme if I know the link.

**Comment by sheldonabrown** [comment]
Which Link?  The repo still has snapshots, so I can probably put the JAR file back if necessary.

http://nexus.onebusaway.org/nexus/content/repositories/snapshots/org/onebusaway/onebusaway-vdv-modules/1.0.0-SNAPSHOT/

**Comment by ustroetz** [comment]
Thanks for the quick response. The Readme contains the link to the Java Jar file: http://nexus.onebusaway.org/service/local/artifact/maven/redirect?r=public&g=org.onebusaway&a=onebusaway-vdv452-to-gtfs-converter-cli&v=LATEST

That is the broken link.

**Comment by sheldonabrown** [comment]
Ok.  I upgraded nexus some time ago, and the API isn't completely compatible with previous versions and / or it moved slightly.  That's most likely the issue.

The files you are looking for are here:
http://nexus.onebusaway.org/nexus/content/repositories/snapshots/org/onebusaway/onebusaway-vdv452-to-gtfs-converter-cli/1.0.0-SNAPSHOT/

If you can figure out the proper way to replace that with the LATEST qualifier, then please, yes, submit a pull request.

**Comment by ustroetz** [comment]
Thanks! I'll have a look.
